FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/*.jar app.jar

# Disable cgroup metrics and file descriptor metrics to avoid Micrometer crash
ENTRYPOINT ["java", "-Djdk.disable.cgroup=true", "-Dmanagement.metrics.binders.files.enabled=false", "-jar", "/app/app.jar"]
